# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD013: Line length - Disabled as it can be too strict for documentation
MD013: false

# MD033: Inline HTML - Allow HTML in Markdown (useful for images, formatting)
MD033: false

# MD041: First line in file should be a top level heading - Disabled
MD041: false

# MD024: Multiple headings with the same content - Allow (useful for changelog)
MD024:
  siblings_only: true

# MD046: Code block style - Enforce fenced code blocks
MD046:
  style: fenced
